# Generated by Django 2.1 on 2019-08-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvn11', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentApp',
        ),
    ]
